### ISSUE TITLE
Can't seem to match Expr

### ISSUE THREAD

**Issue by dbeach24** [kmsquire/Match.jl#21]
I was experimenting to see if I could get `@match` to match an `Expr` (for use in a macro), but immediately hit a wall:

```julia
@match Expr(:call, :+, 1, 2) begin
    Expr(:call, :+, a, b) => "$a plus $b"
    Expr(:call, :-, a, b) => "$a minus $b"
    _ => "Nope!"
end
```
Yields: `"Nope!"`

What am I doing wrong?

**Comment by TotalVerb** [comment]
This works:

```julia
@match Expr(:call, :+, 1, 2) begin
         Expr(:call, [:+, a, b], _) => "$a plus $b"
         Expr(:call, [:-, a, b], _) => "$a minus $b"
         _ => "Nope!"
       end
```

The problem is that `Expr`'s fields are in order: `head`, `args`, `typ`. The constructor for `Expr` creates an `Expr` object from the `Expr(:call, :+, 1, 2)` syntax, but the `Expr` object itself does not have that kind of structure. I'm not sure how this can be solved without hard-coding the `Expr`, since there's not a good way to tell what kind of structure `Constructor(a, b, c, d)` will produce without having the code for `Constructor`.

**Comment by kmsquire** [comment]
See also #7.

In the past, I've thought about special casing `Expr` matching, but never got around to it.

For a usage example, I rewrite `Expr`s using this type of matching in [VideoIO](https://github.com/kmsquire/VideoIO.jl/blob/b99aa023e598dd2e800cb50afa16e6455266b87c/util/wrap_libav_split.jl#L126-L226).
