### ISSUE TITLE
@match on type

### ISSUE THREAD

**Issue by stustd** [kmsquire/Match.jl#34]
The following code doesn't produce identical results (i.e. selecting on type with @match (Match.jl) or if...elseif...end) where I would expect it should: with @match (get_fmt1) regardless of the actual type, always the first type is matched...
```
using Match

function get_fmt1(a)
  T = typeof(a)
  S = supertype(T)
  println("Ta, Sa = $T, $S")
  fmt(a) = @match S begin
    # Signed => "d"
    Integer || Signed || Unsigned || Bool || BigInt => "d"
    AbstractFloat                           => "f"
    AbstractString                          => "s"
    _,Any                                   => "s"
  end
  fmt(a)
end

function get_fmt2(a)
  T = typeof(a)
  S = supertype(T)
  # println("Ta, Sa = $T, $S")
  if S in [Integer Signed Unsigned Bool BigInt ] return "d"
  elseif S == AbstractFloat   return "f"
  elseif S == AbstractString  return "s"
  else return "o"
  end
end

trials = [ 1 1.0 "Foo" Inf ]

println("FMT 1")
for a in  trials
  Ta = typeof(a)
  Sa = supertype(Ta)
  println("a, Ta, Sa = $a, $Ta, $Sa")
  println("fmt a = ", get_fmt1(a))
end

println("FMT 2")
for a in  trials
  Ta = typeof(a)
  Sa = supertype(Ta)
  println("a, Ta, Sa = $a, $Ta, $Sa")
  println("fmt a = ", get_fmt2(a))
end
```

**Comment by kmsquire** [comment]
Hi there, sorry for the slow response.
(I was on vacation and mostly off grid, and just ran across your [Discourse post](https://discourse.julialang.org/t/match-type/1232/1)).

Unfortunately, the `@match` macro is simply rewriting expressions (`Expr`s), and inside of expressions, `Integer` is just a symbol, the same as `a` or `fruitcake`.  So, in your example, the first symbol (`Integer`) will be pattern matched with the value of the variable (e.g., for use to the right of the arrow).  Consider:

```julia
julia> @match 5 begin
          a => print("`a` is ", a)
          _ => print("No match")
       end
`a` is 5
```
and
```julia
julia> @match 5 begin
          Integer => print("Integer is ", Integer)
          _ => print("No match")
       end
Integer is 5
```

There are exceptions/assumptions made when the construct looks like a function call (it's assumed that the "call" is a constructor, and matching then done on the parameters).

In your case, it really doesn't need to be as complicated as you're making it.  You could use either the `_::Type{Integer}` solution, or the more `Julian` way proposed by Tamas Papp, which is a very good choice.  Otherwise, you can use the match macro like this:

```julia
julia> function get_fmt_x(a)
         return @match a begin
           _::Integer || _::Signed || _::Unsigned || _::Bool || _::BigInt => "d"
           _::AbstractFloat                           => "f"
           _::AbstractString                          => "s"
           _                                          => "s"
         end
       end

julia> get_fmt_x(5.0)
"f"

julia> get_fmt_x(5)
"d"
```

(The underscores here are just another variable, and can be replaced with `z` or `fruitcake`, if you prefer.)

Anyway, I assume you've found some solution and moved on, but I hope this was useful.
